name: CI Del1

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIGURATION: Release

    steps:
      - name: Bygg och testa
        uses: actions/checkout@v7

      - name: Install .NET 10
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - name: dotnet Restore
        run: dotnet restore

      - name: dotnet Build
        run: dotnet build --no-restore --configuration ${{env.BUILD_CONFIGURATION}}

      - name: dotnet Test
        run: dotnet test --no-build --configuration ${{env.BUILD_CONFIGURATION}}
      # varför gör vi restore, build och test som tre separata steg istället för ett?
      # Ett steg i staget så den väntar på att steget inna blir klart först.

      - name: INFO
        env: 
          STARTAD_AV: ${{github.actor}}
          HANDELSE: ${{github.event_name}}
          GREN: ${{github.ref_name}}
        run: |
          echo "Startad av $STARTAD_AV — händelse: $HANDELSE — gren: $GREN"
          echo "Startad av $STARTAD_AV — händelse: $HANDELSE — gren: $GREN" > $GITHUB_STEP_SUMMARY
          
